#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcap-ng
Version  : 0.7.7
Release  : 16
URL      : https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.7.7.tar.gz
Source0  : https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.7.7.tar.gz
Summary  : An alternate posix capabilities library
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1 LGPL-2.1+
Requires: libcap-ng-bin
Requires: libcap-ng-lib
Requires: libcap-ng-doc
BuildRequires : python3-dev

%description
Libcap-ng is a library that makes using posix capabilities easier

%package bin
Summary: bin components for the libcap-ng package.
Group: Binaries

%description bin
bin components for the libcap-ng package.


%package dev
Summary: dev components for the libcap-ng package.
Group: Development
Requires: libcap-ng-lib
Requires: libcap-ng-bin

%description dev
dev components for the libcap-ng package.


%package doc
Summary: doc components for the libcap-ng package.
Group: Documentation

%description doc
doc components for the libcap-ng package.


%package lib
Summary: lib components for the libcap-ng package.
Group: Libraries

%description lib
lib components for the libcap-ng package.


%prep
%setup -q -n libcap-ng-0.7.7

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/captest
/usr/bin/filecap
/usr/bin/netcap
/usr/bin/pscap

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
